return {
  -- "olimorris/codecompanion.nvim",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   "nvim-treesitter/nvim-treesitter",
  -- },
  -- config = function()
  --   require("codecompanion").setup({
  --     adapters = {
  --       deepseek = function()
  --         return require("codecompanion.adapters").extend("deepseek", {
  --           env = {
  --             api_key = "",
  --           },
  --           schema = {
  --             model = {
  --               default = "deepseek-coder",
  --               choices = {
  --                 ["deepseek-coder"] = { opts = { can_reason = true } },
  --               },
  --             },
  --           },
  --         })
  --       end,
  --
  --       copilot_claude = function()
  --         return require("codecompanion.adapters").extend("copilot", {
  --           name = "copilot_claude",
  --           schema = {
  --             model = {
  --               default = "claude-3.5-sonnet",
  --             },
  --           },
  --         })
  --       end,
  --     },
  --
  --     strategies = {
  --       chat = { adapter = "deepseek" },
  --       inline = { adapter = "deepseek" },
  --       agent = { adapter = "deepseek" },
  --     },
  --
  --     opts = {
  --       language = "Chinese",
  --     },
  --   })
  -- end,
}
